a & Numpad1::Send "{U+0101}"
a & Numpad2::Send "{U+00E1}"
a & Numpad3::Send "{U+01CE}"
a & Numpad4::Send "{U+00E0}"
a::Send "{a}"
+a::Send "{A}" 

e & Numpad1::Send "{U+0113}"
e & Numpad2::Send "{U+00E9}"
e & Numpad3::Send "{U+011B}"
e & Numpad4::Send "{U+00E8}"
e::Send "{e}"
+e::Send "{E}" 

i & Numpad1::Send "{U+012B}"
i & Numpad2::Send "{U+00ED}"
i & Numpad3::Send "{U+01D0}"
i & Numpad4::Send "{U+00EC}"
i::Send "{i}"
+i::Send "{I}" 

o & Numpad1::Send "{U+014D}"
o & Numpad2::Send "{U+00F3}"
o & Numpad3::Send "{U+01D2}"
o & Numpad4::Send "{U+00F2}"
o::Send "{o}"
+o::Send "{O}" 

u & Numpad1::Send "{U+016B}"
u & Numpad2::Send "{U+00FA}"
u & Numpad3::Send "{U+01D4}"
u & Numpad4::Send "{U+00F9}"
u::Send "{u}"
+u::Send "{U}" 

v & Numpad0::Send "{U+00FC}"
v & Numpad1::Send "{U+01D6}"
v & Numpad2::Send "{U+01D8}"
v & Numpad3::Send "{U+01DA}"
v & Numpad4::Send "{U+01DC}"
v::Send "{v}"
+v::Send "{V}" 
^v::Send "^{v}"



